### ISSUE TITLE
Pass@k Metrics Implementation

### ISSUE THREAD

**Issue by skpig** [zkx06111/ALGO#1]
Awesome work! 
It seems like you use a different implementation of pass@k as mentioned in your paper, "for code synthesizers that do have some techniques for filtering their solutions, pass@k is evaluated by checking whether the top-k programs among the n programs generated can pass the problem. "
Could you please provide code about the metrics calculation?

**Comment by zkx06111** [comment]
I'm really sorry for the late reply.
We followed the definition used by CodeT, so we directly took their code for evaluation.
We refer you to this [repo](https://github.com/microsoft/CodeT/tree/main/CodeT).
